language: java
jdk: openjdk11
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: nh2/C9qNb61chkcKVtV00aO9U5N7RYbIR9V58ODA9FzxDItlEMzFP7pslTkP7hUoWtsVjbKtC7z+fmOc1QoDuSBGEoek6eWATbSHizRrl7sAHQWsKoYTM3XSwnEJr0JpCWja9VXZVZW29t7GBU2zo+nX1blArx/1z7nS62lvKhnk+PshsDFjt99sTX1wopHNIYA/K3tz4hLiHrYj6hv6+4/Un+kyC6GiatxdVu1ahY5sw+oM0+NfT9qmZl7qbG6s4gychr2AcmI/pNdinrocKhZeFs0dZx79d2sVplDxt8B6FiY6yNat7p7f+WqRiQuOljr63TJq4DkX/4lMY3DoVjAqr6auHtw+e86Sr059XWjTAww2ueCziib9KKykgiL5htYlUgcBZEY6BghNJYQuzHHkVQzigqBnOlBiiiu0ByhGC9OHMtyA8CNklXQMo/CfW2IwKyWcyFbMtDjBwQ78dAVdUnOLwwfsJWqyR1l47njCYRPuRytObgpDnllgtmqC9x6RPrpV5CwpMxpuaCGE0jRB9s8t5H+plEINE4cO/vjCg1cFq1THHrckwF+HDpRrJBcESbfSpabcKnzsS4pzkXf9FSUaM4vHorJxrrd3DiUXtzCcEJDDcQ2njS2gHaAnFNTZ54MITMic5PXOjLKwCdrSQxfCL3bOAQ1Erex079w=
